using System.IO;
using RockHoundr.Models;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;


namespace RockHoundr

{
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();

            var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json");

            var configuration = builder.Build();
            var connectionString = configuration.GetConnectionString("MyDb");

            var options = new DbContextOptionsBuilder<gisdbContext>()
                    .UseSqlServer(connectionString)
                    //.UseLoggerFactory(loggerFactory) //Optional, this logs SQL generated by EF Core to the Console
                    .Options;
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
}
